### PR TITLE
Fix double ogv extension

### PR DESCRIPTION
**Pull request by leon-thorsell-simonsen**
Don't understand why we've not seen this before. It did cause a problem with applying conf mgmt at Danish Crown.

### CODE REVIEW

**Review by TobiasWolters — COMMENTED** [review]
🤯 
I guess we have never seen this, because we have never hit a case where we have had to create the media_format_type with configuration management...

If we do this update, won't we then get a diff for existing, "clean" environments?
If you haven't done it already, can you try installing a clean 5.10 with these changes to ensure that it still works?

We also need to make the changes in the `5.10.10` layer.

**Comment by leon-thorsell-simonsen** [comment]
Right, damn, I thought this was an easy one but I agree some testing must be done. It's somewhat likely that will have to wait untill we're on the other side of BigRoomPlanning then.

**Comment by TobiasWolters** [comment]
> Right, damn, I thought this was an easy one but I agree some testing must be done. It's somewhat likely that will have to wait untill we're on the other side of BigRoomPlanning then.

I agree 👍

**Comment by leon-thorsell-simonsen** [comment]
It's a rare corner case and no longer an issue in 6.0+

**Pull request closed without merging**
