### PR TITLE
DAM-6550 Move crop presets to config service

### PR DESCRIPTION
**Pull request by zlepper**
We no longer come with any out of the box, since they are now an independent resource, and thus cannot be removed again. 

I also deleted some unused searches.

### CODE REVIEW

**Review by madjufra — APPROVED** [review]
We dont want to migrate this to another data structure?

**Comment by zlepper** [comment]
> We dont want to migrate this to another data structure?

I already have, there is now a "Crop preset" resource type. However i don't want to come with something out of box in MM, since you cannot delete resource from lower layers. At best we can change them, and that starts coming wierd if they need very custom presets, which is think all customers that use this feature, does.

**Comment by madjufra** [comment]
> > We dont want to migrate this to another data structure?
> 
> I already have, there is now a "Crop preset" resource type. However i don't want to come with something out of box in MM, since you cannot delete resource from lower layers. At best we can change them, and that starts coming wierd if they need very custom presets, which is think all customers that use this feature, does.

One more to the list with regards to migration. They a have ALOT of custom crops and we'll get killed if we do not migrate that for them as part of the upgrade :-)

**Comment by zlepper** [comment]
> > > We dont want to migrate this to another data structure?
> > 
> > 
> > I already have, there is now a "Crop preset" resource type. However i don't want to come with something out of box in MM, since you cannot delete resource from lower layers. At best we can change them, and that starts coming wierd if they need very custom presets, which is think all customers that use this feature, does.
> 
> One more to the list with regards to migration. They a have ALOT of custom crops and we'll get killed if we do not migrate that for them as part of the upgrade :-)

Yep, already on my list :)

**Pull request merged**
