### PR TITLE
removed item security for catalog folders because it doesn't exist an…

### PR DESCRIPTION
**Pull request by Hugzy**
…ymore

### CODE REVIEW

**Review by zlepper — COMMENTED** [review]
This change is only in 5.8 as far as I know, so we should probably make a copy of OOBE for 5.8, and do the changes there instead to avoid breaking 5.7.

@madjufra @leon-thorsell-simonsen Was it 5.8 or 5.7 we removed support for item security for catalog folders? I know the error is new for 5.8, but what about the support itself?

**Comment by TobiasNissen** [comment]
We should also ensure that the `CatalogFolder` type is removed as a whitelisted type in: https://github.com/Digizuite/digizuite.core/blob/master/Apps/ConfigurationManagementService/Resources/Services/ItemSecurityService.cs.

Furthermore, the corresponding integration test for `item_security` for `catalog_folders` should be removed from: https://github.com/Digizuite/digizuite.core/blob/master/Tests/ConfigurationManagementService.Tests/Resources/ItemSecurityTest.cs

**Comment by leon-thorsell-simonsen** [comment]
> This change is only in 5.8 as far as I know, so we should probably make a copy of OOBE for 5.8, and do the changes there instead to avoid breaking 5.7.
> 
> @madjufra @leon-thorsell-simonsen Was it 5.8 or 5.7 we removed support for item security for catalog folders? I know the error is new for 5.8, but what about the support itself?

It's gone with 5.7 at least in the old DC solution. I was never quite aware of what was in the newer code. I think I am about to have a session with Tobias about removing the DCL parts.

**Comment by leon-thorsell-simonsen** [comment]
> We should also ensure that the `CatalogFolder` type is removed as a whitelisted type in: https://github.com/Digizuite/digizuite.core/blob/master/Apps/ConfigurationManagementService/Resources/Services/ItemSecurityService.cs.
> 
> Furthermore, the corresponding integration test for `item_security` for `catalog_folders` should be removed from: https://github.com/Digizuite/digizuite.core/blob/master/Tests/ConfigurationManagementService.Tests/Resources/ItemSecurityTest.cs

**Comment by leon-thorsell-simonsen** [comment]
I have not had food yet, sorry about that.

**Review by TobiasNissen — APPROVED** [review]

**Review by zlepper — APPROVED** [review]

**Pull request merged**
